package com.example.ui.screens

object LanguageText {
    val en = mapOf(
        "title" to "Student Allocation\nList 2026",
        "sub" to "ALLOCATION CHECK",
        "ph" to "Search...",
        "empty" to "No students found",
        "emptySub" to "Try adjusting your filters or search query",
        "btnClose" to "Done",
        "label2025" to "Previous Class (2025)",
        "labelOrigin" to "Primary School (2024)",
        "all" to "All",
        "clear" to "Reset",
        "filter" to "Filter",
        "mLabelCur" to "Current Class",
        "mLabelOld" to "Previous Class",
        "mLabelStat" to "Status",
        "mLabelSch" to "Primary School",
        "mLabelSchPB" to "Previous 2024 Class",
        "labelSort" to "Sort List By",
        "txtName" to "Name",
        "txtClass" to "Class",
        "txtSortBday" to "Birthday",
        "labelStatsTitle" to "Statistics",
        "totalStudents" to "Total Students",
        "statTabOrigin" to "Primary School",
        "statTabOldClass" to "Previous Class",
        "analyzing" to "Analyzing",
        "toastClear" to "Filters Reset",
        "toastFavAdded" to "Added to Favorites",
        "toastFavRem" to "Removed from Favorites",
        "toastFavModeOn" to "Showing Favorites Only",
        "toastFavModeOff" to "Showing All Students",
        "ctxCopy" to "Name Copied",
        "ctxCopyCnToast" to "Chinese Name Copied",
        "ctxCopyIdBtn" to "Copy Student ID",
        "ctxCopyIdToast" to "Student ID Copied",
        "toastCompact" to "Compact Mode Enabled",
        "toastComfort" to "Comfort Mode Enabled",
        "ctxCopyBtn" to "Copy Name",
        "ctxCopyCnBtn" to "Copy Chinese Name",
        "ctxFavBtn" to "Favorite",
        "ctxUnfavBtn" to "Unfavorite",
        "tGuru" to "Class Teacher",
        "tPenolong" to "Assistant Teacher",
        "adminTitle" to "Admin Dashboard",
        "adminSub" to "Changes save to 'Update Queue' locally",
        "tabStudents" to "Students",
        "tabTeachers" to "Classes",
        "tabSettings" to "Settings",
        "tabAudit" to "Audit Log",
        "tabFeedback" to "Feedback",
        "tabAnalytics" to "Analytics",
        "adminAuditTitle" to "Admin Activity Log",
        "adminAuditDesc" to "Tracks detailed changes made in the dashboard.",
        "adminFeedbackTitle" to "User Feedback",
        "adminFeedbackDesc" to "Messages and bug reports submitted by users.",
        "adminAnalyticsTitle" to "System Analytics",
        "adminAnalyticsDesc" to "Overview of user engagement and activity.",
        "statTotalUsers" to "Total Users",
        "statTotalFavs" to "Total Favorites",
        "statRecentActivity" to "Recent User Activity",
        "menuAbout" to "About App",
        "menuHelp" to "Help & Support",
        "menuFeedback" to "Submit Feedback",
        "authEmailPh" to "Email Address",
        "authPassPh" to "Password",
        "authLoginBtn" to "Log In",
        "authSignUpBtn" to "Sign Up",
        "authTitleL" to "Welcome Back",
        "authSubL" to "Log in to view student records",
        "authTitleS" to "Create Account",
        "authSubS" to "Sign up to access records",
        "authToggleL" to "Don't have an account? Sign Up",
        "authToggleS" to "Already have an account? Log In",
        "updateTitleAdded" to "Added Features",
        "updateTitleRemoved" to "Other Changes",
        "updateNext" to "Next",
        "updateDone" to "Done",
        "fbTitle" to "Feedback",
        "fbSub" to "Tell us what you think!",
        "fbPh" to "Type your feedback here...",
        "fbBtn" to "Submit Feedback",
        "toastFb" to "Feedback Submitted!",
        "logoutTitle" to "Log Out?",
        "logoutMsg" to "Are you sure you want to log out of your account?",
        "logoutCancel" to "Cancel",
        "logoutConfirm" to "Log Out",
        "faqTitle" to "Frequently Asked Questions",
        "faqQ1" to "What is the Status icon?",
        "faqA1" to "It shows if a student moved up, down, or stayed the same based on class rankings from 2025 to 2026.",
        "faqQ2" to "How do I search for a student?",
        "faqA2" to "You can use the search bar to type their English Name, Chinese Name, or Student ID.",
        "faqQ3" to "How do I save a student?",
        "faqA3" to "Tap any student and click the Star icon at the top right, or Long Press the student's name on the list.",
        "faqQ4" to "What is Compact View?",
        "faqA4" to "Compact view shrinks the student list and hides avatars so you can see more students at once on your screen.",
        "faqQ5" to "How do I clear my search history?",
        "faqA5" to "Tap the search bar and click the trash can icon next to your recent searches.",
        "faqClose" to "Close",
        "menuHeaderMain" to "Menu",
        "menuThemeDark" to "Dark Mode",
        "menuThemeLight" to "Light Mode",
        "menuDensityCompact" to "Compact View",
        "menuDensityComfort" to "Comfort View",
        "adminThemeTitle" to "Global Website Theme",
        "adminThemeDesc" to "Updates live background for everyone instantly.",
        "adminMaintTitle" to "System Under Maintenance",
        "adminUpdateTitle" to "Startup Update Screen",
        "adminUpdateDesc" to "Shows an overlay upon login to broadcast changes.",
        "adminUICust" to "UI Customization",
        "adminNoGlass" to "Disable Liquid Glass Design",
        "adminHideTheme" to "Hide 'Change Theme' Button",
        "adminHideStats" to "Hide 'Statistics' Button",
        "adminEditAbout" to "Edit 'About' Text",
        "adminForceCoach" to "Force Welcome Guide & Coach Marks",
        "optThemeDyn" to "Dynamic (Changes by Time of Day)",
        "optThemeMorn" to "Locked to Morning Theme",
        "optThemeAft" to "Locked to Afternoon/Day Theme",
        "optThemeNight" to "Locked to Night Theme",
        "optThemeXmas" to "Locked to Festive Christmas Theme",
        "optThemeBeta1" to "New Filter Design (Beta)",
        "optThemeBeta2" to "Secondary Beta UX (Layout Change)",
        "optMaintNo" to "No",
        "optMaintYes" to "Yes (Locks out all users)",
        "optUpdateNo" to "No",
        "optUpdateYes" to "Yes",
        "optGlassNo" to "No (Keep Glassmorphism)",
        "optGlassYes" to "Yes (Solid Colors)",
        "adminAddStudent" to "Add New Student",
        "adminSearchStudent" to "Search by name...",
        "adminIdPlaceholder" to "Student ID (e.g. 120116040351)",
        "adminNamePlaceholder" to "Full Name",
        "adminCnPlaceholder" to "Chinese Name (or -)",
        "adminOldPlaceholder" to "Old Class (e.g. 1B)",
        "adminSchPlaceholder" to "Primary School",
        "adminUpdateQueue" to "Update Queue",
        "adminDelete" to "Delete"
    )

    val bm = mapOf(
        "title" to "Senarai Penempatan\nMurid 2026",
        "sub" to "SEMAKAN PENEMPATAN",
        "ph" to "Cari...",
        "empty" to "Tiada murid dijumpai",
        "emptySub" to "Cuba ubah tapisan atau carian anda",
        "btnClose" to "Selesai",
        "label2025" to "Kelas Terdahulu (2025)",
        "labelOrigin" to "Sekolah Asal (2024)",
        "all" to "Semua",
        "clear" to "Tetap Semula",
        "filter" to "Tapis",
        "mLabelCur" to "Kelas Semasa",
        "mLabelOld" to "Kelas Terdahulu",
        "mLabelStat" to "Status",
        "mLabelSch" to "Sekolah Rendah",
        "mLabelSchPB" to "Kelas 2024",
        "labelSort" to "Susunan Senarai",
        "txtName" to "Nama",
        "txtClass" to "Kelas",
        "txtSortBday" to "Hari Jadi",
        "labelStatsTitle" to "Statistik",
        "totalStudents" to "Jumlah Murid",
        "statTabOrigin" to "Sekolah Asal",
        "statTabOldClass" to "Kelas Terdahulu",
        "analyzing" to "Menganalisis",
        "toastClear" to "Tapisan Dikosongkan",
        "toastFavAdded" to "Ditambah ke Kegemaran",
        "toastFavRem" to "Dibuang dari Kegemaran",
        "toastFavModeOn" to "Papar Kegemaran Sahaja",
        "toastFavModeOff" to "Papar Semua Murid",
        "ctxCopy" to "Nama Disalin",
        "ctxCopyCnToast" to "Nama Cina Disalin",
        "ctxCopyIdBtn" to "Salin ID Murid",
        "ctxCopyIdToast" to "ID Murid Disalin",
        "toastCompact" to "Mod Padat Diaktifkan",
        "toastComfort" to "Mod Selesa Diaktifkan",
        "ctxCopyBtn" to "Salin Nama",
        "ctxCopyCnBtn" to "Salin Nama Cina",
        "ctxFavBtn" to "Simpan",
        "ctxUnfavBtn" to "Batal Simpan",
        "tGuru" to "Guru Kelas",
        "tPenolong" to "Penolong",
        "adminTitle" to "Papan Pemuka Admin",
        "adminSub" to "Perubahan disimpan ke 'Barisan' secara lokal",
        "tabStudents" to "Murid",
        "tabTeachers" to "Kelas",
        "tabSettings" to "Tetapan",
        "tabAudit" to "Log Audit",
        "tabFeedback" to "Maklum Balas",
        "tabAnalytics" to "Analitik",
        "adminAuditTitle" to "Log Aktiviti Admin",
        "adminAuditDesc" to "Menjejaki perubahan terperinci yang dibuat dalam papan pemuka.",
        "adminFeedbackTitle" to "Maklum Balas Pengguna",
        "adminFeedbackDesc" to "Mesej dan laporan pepijat daripada pengguna.",
        "adminAnalyticsTitle" to "Analitik Sistem",
        "adminAnalyticsDesc" to "Gambaran keseluruhan penglibatan dan aktiviti pengguna.",
        "statTotalUsers" to "Jumlah Pengguna",
        "statTotalFavs" to "Jumlah Kegemaran",
        "statRecentActivity" to "Aktiviti Pengguna Terkini",
        "menuAbout" to "Mengenai Aplikasi",
        "menuHelp" to "Bantuan & Sokongan",
        "menuFeedback" to "Hantar Maklum Balas",
        "authEmailPh" to "Alamat E-mel",
        "authPassPh" to "Kata Luan",
        "authLoginBtn" to "Log Masuk",
        "authSignUpBtn" to "Daftar",
        "authTitleL" to "Selamat Kembali",
        "authSubL" to "Log masuk untuk melihat rekod murid",
        "authTitleS" to "Cipta Akaun",
        "authSubS" to "Daftar untuk mengakses rekod",
        "authToggleL" to "Tiada akaun? Daftar sahaja",
        "authToggleS" to "Sudah ada akaun? Log Masuk",
        "updateTitleAdded" to "Ciri-ciri Baharu",
        "updateTitleRemoved" to "Perubahan Lain",
        "updateNext" to "Seterusnya",
        "updateDone" to "Selesai",
        "fbTitle" to "Maklum Balas",
        "fbSub" to "Beritahu kami pendapat anda!",
        "fbPh" to "Taipkan maklum balas anda di sini...",
        "fbBtn" to "Hantar Maklum Balas",
        "toastFb" to "Maklum Balas Dihantar!",
        "logoutTitle" to "Log Keluar?",
        "logoutMsg" to "Adakah anda pasti ingin log keluar dari akaun anda?",
        "logoutCancel" to "Batal",
        "logoutConfirm" to "Log Keluar",
        "faqTitle" to "Soalan Lazim (FAQ)",
        "faqQ1" to "Apakah maksud ikon Status?",
        "faqA1" to "Ia menunjukkan sama ada murid naik, turun, atau kekal sama berdasarkan kelas lama berbanding kelas baru.",
        "faqQ2" to "Bagaimana cara mencari murid?",
        "faqA2" to "Anda boleh menggunakan bar carian untuk menaip Nama Inggeris, Nama Cina, atau ID Murid.",
        "faqQ3" to "Bagaimana cara menyimpan murid?",
        "faqA3" to "Ketik mana-mana murid dan klik ikon Bintang di kanan atas, atau Tekan Lama pada murid di senarai.",
        "faqQ4" to "Apakah itu Paparan Padat?",
        "faqA4" to "Paparan padat mengecilkan senarai murid dan menyembunyikan avatar untuk menjimatkan ruang pada skrin.",
        "faqQ5" to "Bagaimana cara memadam sejarah carian?",
        "faqA5" to "Ketik bar carian dan klik ikon tong sampah di sebelah sejarah carian.",
        "faqClose" to "Tutup",
        "menuHeaderMain" to "Menu",
        "menuThemeDark" to "Mod Gelap",
        "menuThemeLight" to "Mod Terang",
        "menuDensityCompact" to "Paparan Padat",
        "menuDensityComfort" to "Paparan Selesa",
        "adminThemeTitle" to "Tema Laman Web Global",
        "adminThemeDesc" to "Kemas kini latar belakang secara langsung untuk semua.",
        "adminMaintTitle" to "Sistem Sedang Diselenggara",
        "adminUpdateTitle" to "Skrin Kemas Kini Log Masuk",
        "adminUpdateDesc" to "Papar tetingkap untuk memaklumkan perubahan.",
        "adminUICust" to "Penyesuaian Antara Muka (UI)",
        "adminNoGlass" to "Lumpuhkan Reka Bentuk Kaca (Glassmorphism)",
        "adminHideTheme" to "Sembunyi Butang 'Tukar Tema'",
        "adminHideStats" to "Sembunyi Butang 'Statistik'",
        "adminEditAbout" to "Sunting Teks 'Mengenai Aplikasi'",
        "adminForceCoach" to "Paksa Panduan Selamat Datang & Tanda Jurulatih",
        "optThemeDyn" to "Dinamik (Berubah Mengikut Waktu)",
        "optThemeMorn" to "Dikunci pada Tema Pagi",
        "optThemeAft" to "Dikunci pada Tema Petang/Siang",
        "optThemeNight" to "Dikunci pada Tema Malam",
        "optThemeXmas" to "Dikunci pada Tema Krismas",
        "optThemeBeta1" to "Reka Bentuk Tapisan Baharu (Beta)",
        "optThemeBeta2" to "UX Beta Kedua (Perubahan Susun Atur)",
        "optMaintNo" to "Tidak",
        "optMaintYes" to "Ya (Menghalang log masuk)",
        "optUpdateNo" to "Tidak",
        "optUpdateYes" to "Ya",
        "optGlassNo" to "Tidak (Kekalkan Reka Bentuk Kaca)",
        "optGlassYes" to "Ya (Warna Pepejal)",
        "adminAddStudent" to "Tambah Murid Baharu",
        "adminSearchStudent" to "Cari berdasarkan nama...",
        "adminIdPlaceholder" to "ID Murid (cth. 120116040351)",
        "adminNamePlaceholder" to "Nama Penuh",
        "adminCnPlaceholder" to "Nama Cina (atau -)",
        "adminOldPlaceholder" to "Kelas Lama (cth. 1B)",
        "adminSchPlaceholder" to "Sekolah Rendah",
        "adminUpdateQueue" to "Barisan Kemas Kini",
        "adminDelete" to "Padam"
    )

    val cn = mapOf(
        "title" to "2026年学生\n分班名单",
        "sub" to "分班查询",
        "ph" to "搜索...",
        "empty" to "未找到学生",
        "emptySub" to "尝试调整您的筛选条件或搜索词",
        "btnClose" to "完成",
        "label2025" to "2025 原班级",
        "labelOrigin" to "2024 毕业小学",
        "all" to "全部",
        "clear" to "重置",
        "filter" to "筛选",
        "mLabelCur" to "分配班级",
        "mLabelOld" to "原班级",
        "mLabelStat" to "状态",
        "mLabelSch" to "毕业小学",
        "mLabelSchPB" to "2024年班级",
        "labelSort" to "排序方式",
        "txtName" to "姓名",
        "txtClass" to "班级",
        "txtSortBday" to "生日",
        "labelStatsTitle" to "数据统计",
        "totalStudents" to "总学生数",
        "statTabOrigin" to "毕业小学",
        "statTabOldClass" to "原班级",
        "analyzing" to "正在分析",
        "toastClear" to "已重置筛选",
        "toastFavAdded" to "已收藏",
        "toastFavRem" to "已取消收藏",
        "toastFavModeOn" to "仅显示收藏",
        "toastFavModeOff" to "显示所有学生",
        "ctxCopy" to "姓名已复制",
        "ctxCopyCnToast" to "中文名已复制",
        "ctxCopyIdBtn" to "复制学生 ID",
        "ctxCopyIdToast" to "学生 ID 已复制",
        "toastCompact" to "紧凑模式已启用",
        "toastComfort" to "舒适模式已启用",
        "ctxCopyBtn" to "复制姓名",
        "ctxCopyCnBtn" to "复制中文名",
        "ctxFavBtn" to "收藏",
        "ctxUnfavBtn" to "取消收藏",
        "tGuru" to "班主任",
        "tPenolong" to "副班主任",
        "adminTitle" to "管理员仪表板",
        "adminSub" to "更改将本地保存到更新队列",
        "tabStudents" to "学生",
        "tabTeachers" to "班级",
        "tabSettings" to "设置",
        "tabAudit" to "审计日志",
        "tabFeedback" to "用户反馈",
        "tabAnalytics" to "数据分析",
        "adminAuditTitle" to "管理员活动日志",
        "adminAuditDesc" to "记录在仪表板中所做的详细更改。",
        "adminFeedbackTitle" to "用户反馈",
        "adminFeedbackDesc" to "用户提交的反馈和错误报告。",
        "adminAnalyticsTitle" to "系统分析",
        "adminAnalyticsDesc" to "用户参与度和活动概览。",
        "statTotalUsers" to "总用户数",
        "statTotalFavs" to "总收藏数",
        "statRecentActivity" to "最近用户活动",
        "menuAbout" to "关于应用",
        "menuHelp" to "帮助与支持",
        "menuFeedback" to "提交反馈",
        "authEmailPh" to "电子邮件地址",
        "authPassPh" to "密码",
        "authLoginBtn" to "登录",
        "authSignUpBtn" to "注册",
        "authTitleL" to "欢迎回来",
        "authSubL" to "登录以查看学生记录",
        "authTitleS" to "创建账户",
        "authSubS" to "注册以访问记录",
        "authToggleL" to "没有账户？注册",
        "authToggleS" to "已有账户？登录",
        "updateTitleAdded" to "新增功能",
        "updateTitleRemoved" to "其他更改",
        "updateNext" to "下一步",
        "updateDone" to "完成",
        "fbTitle" to "反馈",
        "fbSub" to "告诉我们您的想法！",
        "fbPh" to "在此输入您的反馈...",
        "fbBtn" to "提交反馈",
        "toastFb" to "反馈已提交！",
        "logoutTitle" to "登出？",
        "logoutMsg" to "您确定要登出您的账户吗？",
        "logoutCancel" to "取消",
        "logoutConfirm" to "登出",
        "faqTitle" to "常见问题 (FAQ)",
        "faqQ1" to "状态图标是什么意思？",
        "faqA1" to "它显示学生从2025年到2026分配班级的排名方向（升序、降序或不变）。",
        "faqQ2" to "如何搜索学生？",
        "faqA2" to "您可以使用搜索栏输入他们的英文名、中文名或学生ID。",
        "faqQ3" to "如何收藏学生？",
        "faqA3" to "点击任何学生，然后点击右上角的星形图标，或在列表上长按学生姓名。",
        "faqQ4" to "什么是紧凑视图？",
        "faqA4" to "紧凑视图会缩卡片尺寸，隐藏大图标，让屏幕能显示更多学生。",
        "faqQ5" to "如何清除搜索历史？",
        "faqA5" to "点击搜索栏并在历史词条末端选择清除按钮即可删除历史记录。",
        "faqClose" to "关闭",
        "menuHeaderMain" to "菜单",
        "menuThemeDark" to "深色模式",
        "menuThemeLight" to "浅色模式",
        "menuDensityCompact" to "紧凑视图",
        "menuDensityComfort" to "舒适视图",
        "adminThemeTitle" to "全局网站主题",
        "adminThemeDesc" to "即时为所有人更新动态背景。",
        "adminMaintTitle" to "系统维护中",
        "adminUpdateTitle" to "登录更新屏幕",
        "adminUpdateDesc" to "登录时显示弹窗以广播更新情况。",
        "adminUICust" to "界面 (UI) 自定义",
        "adminNoGlass" to "禁用玻璃拟态设计",
        "adminHideTheme" to "隐藏“切换主题”按钮",
        "adminHideStats" to "隐藏“数据统计”按钮",
        "adminEditAbout" to "编辑“关于应用”文本",
        "adminForceCoach" to "强制显示欢迎指南和提示",
        "optThemeDyn" to "动态 (随时间变化)",
        "optThemeMorn" to "锁定为早晨主题",
        "optThemeAft" to "锁定为下午/白天主题",
        "optThemeNight" to "锁定为夜晚主题",
        "optThemeXmas" to "锁定为圣诞节主题",
        "optThemeBeta1" to "新筛选器设计 (测试版)",
        "optThemeBeta2" to "次要测试版UX (布局更改)",
        "optMaintNo" to "否",
        "optMaintYes" to "是 (锁定所有用户)",
        "optUpdateNo" to "否",
        "optUpdateYes" to "是",
        "optGlassNo" to "否 (保留玻璃拟态)",
        "optGlassYes" to "是 (纯色)",
        "adminAddStudent" to "添加新学生",
        "adminSearchStudent" to "按姓名搜索...",
        "adminIdPlaceholder" to "学生 ID (例: 120116040351)",
        "adminNamePlaceholder" to "全名",
        "adminCnPlaceholder" to "中文名 (或 -)",
        "adminOldPlaceholder" to "原班级 (例: 1B)",
        "adminSchPlaceholder" to "毕业小学",
        "adminUpdateQueue" to "更新队列",
        "adminDelete" to "删除"
    )

    fun getText(lang: String, key: String): String {
        val dict = when (lang.lowercase()) {
            "bm" -> bm
            "cn" -> cn
            else -> en
        }
        return dict[key] ?: en[key] ?: key
    }
}
